#!/bin/bash

KBINDIR=~/kbin
TARGET=$1
shift 1
OPTS=$*

perr() { # message
  echo "Error: "$1
  exit 0
}

check_gitdir() { # dir
  test -d $1/.git
}

exist() { # binary
  which $1 &> /dev/null
}

check_gitdir $PWD || perr "Failed to find git repository in $PWD"

# Setup arch and cross compile environment
if [ -z "$ARCH" ]; then
  ARCH=`uname -m`
fi
CROSS_COMPILE=
case $ARCH in
  i*86)
    ARCH=x86
  ;;
  arm)
    CROSS_COMPILE=arm-linux-gnueabihf-
    exist ${CROSS_COMPILE}gcc || CROSS_COMPILE=arm-linux-gnueabi-
  ;;
  arm64|aarch64)
    ARCH=arm64
    CROSS_COMPILE=aarch64-linux-gnu-
  ;;
esac
echo "Make a $ARCH kernel"
if [ "$CROSS_COMPILE" ]; then
  if exist ${CROSS_COMPILE}gcc; then
    echo "Use ${CROSS_COMPILE}gcc for cross build"
  else
    perr "Failed to find cross build tool. Please install ${CROSS_COMPILE}gcc."
  fi
fi
export ARCH
export CROSS_COMPILE

SRCDIR=$PWD
BINDIR=$KBINDIR/`basename $PWD`.$ARCH

[ -d $BINDIR ] || mkdir -p $BINDIR || perr "Failed to make kbindir"

#KREL=`make kernelrelease`

NR_CPUS=`grep processor /proc/cpuinfo | wc -l`
JOBS=`expr $NR_CPUS \* 2`
SUDO=

do_make() { # target options
  echo make O=$BINDIR -j$JOBS $*
  $SUDO make O=$BINDIR -j$JOBS $*
}

sudo_make() { #target options
  SUDO=sudo 
  do_make $*
}

do_make_log() { # target options
  do_make $* 2>&1 | tee make.log
  grep '^[a-zA-Z/].*' make.log > error.log
}

copy_config() { #file
  if [ "$1" -a -f "$1" ]; then
    cp -f $1 $BINDIR/.config
  else
    [ -f /boot/config-`uname -r` ] && \
      cp -f /boot/config-`uname -r` $BINDIR/.config && return
    [ -f /proc/config.gz ] && \
      zcat /proc/config.gz > $BINDIR/.config && return
    [ -f /proc/config ] && \
      cat /proc/config > $BINDIR/.config && return
  fi
}

cscope_run() {
  if [ ! -f $BINDIR/cscope.out ]; then
    JOBS=1
    do_make cscope
  fi
  cscope -d -f $BINDIR/cscope.out
}

case $TARGET in
 copyconfig)
   copy_config $OPTS
   ls -a $BINDIR
   do_make oldconfig
 ;;
 alllog)
   do_make_log all $OPTS
 ;;
 kinstall)
   JOBS=1
   sudo_make modules_install install 
 ;;
 cscope)
   cscope_run
 ;;
 help)
 ;;
 *)
   do_make $TARGET
 ;;
esac
